### ISSUE TITLE
wpcap.dll is missing

### ISSUE THREAD

**Issue by hydra1983** [robertdavidgraham/masscan#11]
I got this error when I run it on windows:
![image](https://f.cloud.github.com/assets/488235/1170833/b41e7274-20f0-11e3-896a-83ac1f20e286.png)

**Comment by atikrahman1** [comment]
I confirm the solution provided by @hydra1983  is still working in 

```
Microsoft Windows 10 Pro
Masscan version 1.0.3 ( https://github.com/robertdavidgraham/masscan )
Compiled on: Apr 16 2016 10:40:57
Compiler: VisualStudio post-2013
OS: Windows
CPU: x86 (32 bits)
```

thanks
