### ISSUE TITLE
Potential Memory Leak?

### ISSUE THREAD

**Issue by 735tesla** [robertdavidgraham/masscan#152]
It seems that the memory associated with `new_filename` in output.c line 553 might never be freed.

<pre>
new_filename = (char*)malloc(new_filename_size);
    if (new_filename == NULL) {
        LOG(0, "rotate: out of memory error\n");
        return out->fp;
    }

    /* Get the proper timestamp for the file */
    if (out->is_gmt) {
        err = gmtime_s(&tm, &out->rotate.last);
    } else {
        err = localtime_s(&tm, &out->rotate.last);
    }
    if (err != 0) {
        perror("gmtime(): file rotation ended");
        return out->fp; // at this point malloc was successful and we return without freeing the memory associated with new_filename
    }
</pre>

I'm no expert so I could be wrong, but it seems like a memory leak to me

**Comment by agreene5** [comment]
@735tesla the pointer is stored in a struct Output structure, if you follow it you will see it is later free()'d in output.c:931:

```
void
output_destroy(struct Output *out)
{
...
    free(out->filename);
...
}
```

This issue can safely be closed
