### ISSUE TITLE
i need an installation guide for this tool

### ISSUE THREAD

**Issue by sanampuri** [robertdavidgraham/masscan#169]
i am unable to install masscan on my kalilinux, can any one tells how to do it.

**Comment by brammittendorff** [comment]
i do not think it is ment for but for servers with a 10gbps port or a 1gbps port, but you can always try to:
$ sudo apt-get install git gcc make libpcap-dev
$ git clone https://github.com/robertdavidgraham/masscan
$ cd masscan
$ make

**Comment by sanampuri** [comment]
i Got it Solved, The Issue is with Kali Os, The Os Image i Used Not Allowing the Internet on it, i Figured it and Used Kali Os from kali Website and the Tool Worked, Thanks for the Support guys.
