### ISSUE TITLE
TOR & masscan

### ISSUE THREAD

**Issue by jteslaxxx** [robertdavidgraham/masscan#197]
Hello Robert!

First its not issue more than question!
I was wondering is it possible to configure masscan to pass traffic threw TOR? I tried it out , tor bundle is registrating that masscan is connecting to tor, but when i look on dns requests in wireshark, i can see that its not passing proxychains! 

 Thanks!

**Comment by aaronkaplan** [comment]
> On 16 Nov 2015, at 11:11, jteslaxxx <notifications@github.com> wrote:
> 
> Hello Robert!
> 
> First its not issue more than question!
> I was wondering is it possible to configure masscan to pass traffic threw TOR? I tried it out , tor bundle is registrating that masscan is connecting to tor, but when i look on dns requests in wireshark, i can see that its not passing proxy chains!

Oh, that’s a very interesting way to successfully DDOS the tor network ;-)

**Comment by jteslaxxx** [comment]
understood you!:)

**Comment by jteslaxxx** [comment]
thanks

**Comment by jteslaxxx** [comment]
But

**Comment by larrycameron80** [comment]
Is it possible?

**Comment by apacketofsweets** [comment]
Masscan uses it's own TCP/IP stack, which would explain why the traffic isn't passing through proxychains. So no, I don't believe to currently be possible unless you configure some form of firewall based routing setup on your machine.

**Comment by larrycameron80** [comment]
It behaves similar to NMAP so if you used this command line option and had a list of generated .onion addresses then it might work. Might have to "Torrify" the application first for it to work.

**-iL filename: Read inputs from a file.**
