### ISSUE TITLE
Error while compiling on Raspberry Pi 2

### ISSUE THREAD

**Issue by ravkr** [robertdavidgraham/masscan#200]
root@pi:/home/data/masscan # make
    gcc -g -ggdb    -Wall -O3 -c src/smackqueue.c -o tmp/smackqueue.o
    gcc -g -ggdb    -Wall -O3 -c src/string_s.c -o tmp/string_s.o
    gcc -g -ggdb    -Wall -O3 -c src/output.c -o tmp/output.o
    gcc -g -ggdb    -Wall -O3 -c src/proto-ntp.c -o tmp/proto-ntp.o
    gcc -g -ggdb    -Wall -O3 -c src/proto-dns.c -o tmp/proto-dns.o
    gcc -g -ggdb    -Wall -O3 -c src/ranges.c -o tmp/ranges.o
    gcc -g -ggdb    -Wall -O3 -c src/proto-imap4.c -o tmp/proto-imap4.o
    gcc -g -ggdb    -Wall -O3 -c src/rawsock-pcapfile.c -o tmp/rawsock-pcapfile.o
    gcc -g -ggdb    -Wall -O3 -c src/proto-x509.c -o tmp/proto-x509.o
    gcc -g -ggdb    -Wall -O3 -c src/proto-http.c -o tmp/proto-http.o
    gcc -g -ggdb    -Wall -O3 -c src/proto-tcp-telnet.c -o tmp/proto-tcp-telnet.o
    gcc -g -ggdb    -Wall -O3 -c src/pixie-file.c -o tmp/pixie-file.o
    gcc -g -ggdb    -Wall -O3 -c src/main.c -o tmp/main.o
    gcc -g -ggdb    -Wall -O3 -c src/in-filter.c -o tmp/in-filter.o
    gcc -g -ggdb    -Wall -O3 -c src/out-grepable.c -o tmp/out-grepable.o
    gcc -g -ggdb    -Wall -O3 -c src/rawsock-getroute.c -o tmp/rawsock-getroute.o
    gcc -g -ggdb    -Wall -O3 -c src/main-conf.c -o tmp/main-conf.o -DGIT=\"1.0.3-98-g0cac045\"
    gcc -g -ggdb    -Wall -O3 -c src/proto-interactive.c -o tmp/proto-interactive.o
    gcc -g -ggdb    -Wall -O3 -c src/out-redis.c -o tmp/out-redis.o
    gcc -g -ggdb    -Wall -O3 -c src/proto-tcp.c -o tmp/proto-tcp.o
    gcc -g -ggdb    -Wall -O3 -c src/proto-vnc.c -o tmp/proto-vnc.o
    gcc -g -ggdb    -Wall -O3 -c src/proto-ftp.c -o tmp/proto-ftp.o
    gcc -g -ggdb    -Wall -O3 -c src/rand-primegen.c -o tmp/rand-primegen.o
    gcc -g -ggdb    -Wall -O3 -c src/proto-ssl.c -o tmp/proto-ssl.o
    gcc -g -ggdb    -Wall -O3 -c src/rawsock-getip.c -o tmp/rawsock-getip.o
    gcc -g -ggdb    -Wall -O3 -c src/rand-lcg.c -o tmp/rand-lcg.o
    gcc -g -ggdb    -Wall -O3 -c src/crypto-base64.c -o tmp/crypto-base64.o
    gcc -g -ggdb    -Wall -O3 -c src/main-initadapter.c -o tmp/main-initadapter.o
    gcc -g -ggdb    -Wall -O3 -c src/siphash24.c -o tmp/siphash24.o
    gcc -g -ggdb    -Wall -O3 -c src/proto-preprocess.c -o tmp/proto-preprocess.o
    gcc -g -ggdb    -Wall -O3 -c src/rawsock.c -o tmp/rawsock.o
    src/rawsock.c:16:18: fatal error: pcap.h: No such file or directory
     #include <pcap.h>
                      ^
    compilation terminated.
    Makefile:87: recipe for target 'tmp/rawsock.o' failed
    make: *** [tmp/rawsock.o] Error 1

    root@pi:/home/data/masscan # uname -a
    Linux pi 4.1.13-v7+ #826 SMP PREEMPT Fri Nov 13 20:19:03 GMT 2015 armv7l GNU/Linux

how can I fix this?

**Comment by JanBerktold** [comment]
You need to have libpcap installed.

Should go something like this
    ```sudo apt-get install libpcap-dev```

**Comment by ravkr** [comment]
Thank you for help :)
