### ISSUE TITLE
Update README: Examples do not work

### ISSUE THREAD

**Issue by leonklingele** [robertdavidgraham/masscan#248]
I tried to scan the entire Internet (lol!) like suggested in the README:
`masscan 0.0.0.0/0 -p0-65535`

This however fails:

```
FAIL: no ports were specified
 [hint] try something like "-p80,8000-9000"
 [hint] try something like "--ports 0-65535"
```

`masscan 0.0.0.0/0 --ports 0-65535` works fine.

**Comment by ravkr** [comment]
someone tried to fix #233 and it broke -p option :/ use --ports instead

**Comment by ravkr** [comment]
this should be closed now

**Comment by leonklingele** [comment]
Thanks for the fix, @ravkr! :)
