### ISSUE TITLE
Created Global Exclude List

### ISSUE THREAD

**Issue by DarrenRainey** [robertdavidgraham/masscan#266]
For anyone wanting it I have create an exclude list to avoid getting abuse complaints here : https://github.com/DarrenRainey/Global-Masscan-Blacklist

**Comment by nixawk** [comment]
- https://en.wikipedia.org/wiki/Reserved_IP_addresses
- https://en.wikipedia.org/wiki/List_of_assigned_/8_IPv4_address_blocks
