### ISSUE TITLE
error on windows:FAIL: Error opening adapter:The system cannot find the device specified

### ISSUE THREAD

**Issue by chuanjiesun** [robertdavidgraham/masscan#273]
I am using mingw  to compile masscan on windows(win10,win2008),and I install winpcap on the machine,when I run masscan.exe,an error occured: Error opening adapter:The system cannot find the device specified,adapter[\Device\NPF_{56376F12-E110-42B8-9741-3C6293EAC0ED}].init: failed.
how to fix this error?

**Comment by helperroropeningadapter** [comment]
I think,you should download ReimageRepair

**Comment by helperroropeningadapter** [comment]
https://www.a2zcrack.com/2015/04/reimage-repair-key/

**Comment by pishgaman-org** [comment]
it is an old question but if anyone has this problem just should run it as administrator.

**Comment by borune-k12** [comment]
running under admin doesn't solve this issue under win10

**Comment by shyixiu** [comment]
> it is an old question but if anyone has this problem just should run it as administrator.

it doesn't work
