### ISSUE TITLE
-oJ with multiprocessing error

### ISSUE THREAD

**Issue by c0rpse** [robertdavidgraham/masscan#281]
When I use multiprocessing to run masscan with Python, the output file contains all scan result of the ips.
For Example,child process A is specified to scan 192.168.2.2 with output option -oJ a.json and B is used to scan 192.168.2.3 with output option -oJ b.json, however a.json contains both A and B when process finished.That's not what I want.
This's a concunrrency problem.

**Comment by mzpqnxow** [comment]
use a different --adapter-port for each scan

Also, why are you doing this?

**Comment by mzpqnxow** [comment]
Use a different --adapter-port for each scan

What is your use, why are you doing this?

**Comment by mzpqnxow** [comment]
@c0rpse, see above

**Comment by c0rpse** [comment]
@mzpqnxow It seems that -c param caused this problem.When I try to use configuration file to run scan tasks with several  concunrrency processes,result is confused.But without configuration file,command line params  run normally. Lines below is my masscan configuration content:
`rate =   100000.00
randomize-hosts = true
seed =
shard = 1/1
banners = true
adapter =
adapter-ip = 0.0.0.0
adapter-mac = 00:00:00:00:00:00
router-mac = 00:00:00:00:00:00
output-format = unknown(0)
show = open,,
output-filename =
rotate = 0
rotate-dir = .
rotate-offset = 0
rotate-filesize = 0
pcap =
retries = 0
ports =1-1024,1080,1423,1434,3306,8081,8080,3128,8000,8001,8080,8888

capture = cert
nocapture = html
nocapture = heartbleed
nocapture = ticketbleed

min-packet = 60`

Does 'seed' caused this?

As for my use, I wanna scan several individual targets simultaneously in order to reduce time used.

**Comment by mzpqnxow** [comment]
I forgot there was a seed parameter but yes, if you're setting the seed to
the same in both it might confuse things when running on the same host. Try
using different seeds. I still don't understand why you're running multiple
scans at once on one host. Sharding is really meant for scans on different
interfaces or hosts (which would also solve the problem, but probably isn't
what you want)

**Comment by mzpqnxow** [comment]
By the way, without using adapter-port in conjunction with iptables you're
going to have problems picking up banners. See the README if you don't know
what I'm talking about

**Comment by c0rpse** [comment]
@mzpqnxow Thanks a lot.I'll try to use adapter-port in conjunction with iptables.By the way, English is not my mother tongue.I hope you'll excuse me for the grammatical mistakes that occurred.
