### ISSUE TITLE
UDP Scanning Not Working

### ISSUE THREAD

**Issue by danielmiessler** [robertdavidgraham/masscan#342]
Hey Robert,

It looks like UDP scanning isn't working, even with an update of the latest code as of a few minutes ago.

If you scan for UDP 53 on 4.2.2.2 (a Google name server) you get a result with Nmap but not with Masscan. I've tried multiple ways of doing:

--udp-ports 53
-sU -p 53
-pU:53

None of them are working.

Thanks for the great tool though!

**Comment by danielmiessler** [comment]
This has been addressed.

**Comment by altjx** [comment]
@danielmiessler,

How'd you get this to work? Mine seems to perform a SYN Stealth scan by default, even when specifying `-pU:53`
