### ISSUE TITLE
grepable output (Nmap -oG) it's missing the service name

### ISSUE THREAD

**Issue by riramar** [robertdavidgraham/masscan#362]
Other tools are breaking since it expect the service name on the output file.

```
# /root/masscan/bin/masscan -p22 x.x.x.x -oG ./test1

Starting masscan 1.0.6 (http://bit.ly/14GZzcT) at 2018-07-09 21:01:55 GMT
 -- forced options: -sS -Pn -n --randomize-hosts -v --send-eth
Initiating SYN Stealth Scan
Scanning 1 hosts [1 port/host]
# nmap -p22 x.x.x.x -n -oG ./test2
Starting Nmap 7.70 ( https://nmap.org ) at 2018-07-09 18:03 -03
Nmap scan report for x.x.x.x
Host is up (0.29s latency).

PORT   STATE SERVICE
22/tcp open  ssh

Nmap done: 1 IP address (1 host up) scanned in 0.87 seconds
# grep Ports test1 | grep open && grep Ports test2 | grep open
Host: x.x.x.x ()	Ports: 22/open/tcp////
Host: x.x.x.x ()	Ports: 22/open/tcp//ssh///
```

**Comment by mzpqnxow** [comment]
I believe I implemented this in the rarely used unicornscan output format
feature I added a long time ago. Check the code in that file
(output-unicornscan.c or something), as it’s very very simple to port (not
a pun)and I think Rob added proper behavior for doing it on Windows (I did
only Linux)

**Comment by robertdavidgraham** [comment]
I changed how unicornscan.c does it, moved it into new files, and added to greppable output, so it should work now. Try it out and re-open this issue if it doesn't work.
