### ISSUE TITLE
xml output format with --stylesheet "nmap.xsl"

### ISSUE THREAD

**Issue by kaitoan2000** [robertdavidgraham/masscan#364]
Hi Robert,
Could we have a pretty xml format with a --stylesheet like nmap?
Regards,

**Comment by mzpqnxow** [comment]
Why is JSON not able to solve your problem? And aren’t there json2xml
converters?

Unlike grep and json, seems XML would require a third party dependency and
could be an invasive integration. I’m really curious what the use case is
for it, not just being difficult (though my disdain for XML is well known
and it was implemented particularly poorly in nmap in my opinion.

**Comment by kaitoan2000** [comment]
A web-view with .xml report group by ip/hostname and all ports. *Something like this*
![enter image description here](https://b.f7.group.zp.zdn.vn/4859049381927995949/b0e9038606b1e7efbea0.jpg)	
Thanks

**Comment by kaitoan2000** [comment]
I think It should be nice with it.
*For viewing or translating XML output to HTML..*

> https://svn.nmap.org/nmap/docs/nmap.xsl

**Comment by robertdavidgraham** [comment]
Doesn't masscan already support this? I just ran this:

$ bin/masscan 23.23.23.0/24 -p80 --banners --stylesheet foo -oX foo.xml

Starting masscan 1.0.6 (http://bit.ly/14GZzcT) at 2018-07-23 20:21:06 GMT
 -- forced options: -sS -Pn -n --randomize-hosts -v --send-eth
Initiating SYN Stealth Scan
Scanning 256 hosts [1 port/host]
$ grep style foo.xml                                                         
<?xml-stylesheet href="foo" type="text/xsl"?>

However, when I apply the nmap stylesheet (nmap.xsl) it produces a blank screen. I'm not sure why. Do I have a syntax error somewhere?

**Comment by robertdavidgraham** [comment]
I'm going to close this issue, but please open another issue if you can't get it to work. Better yet, write a stylesheet I can set as the default, and put it in "~/masscan/data/masscan.xsl" and do a pull request.

**Comment by FabioPedretti** [comment]
I tried myself, it works, however it should need a proper stylesheet because the nmap one is doesn't fit well (i.e. missing banners info).
