### ISSUE TITLE
Best Rate For best result

### ISSUE THREAD

**Issue by H1-N1** [robertdavidgraham/masscan#373]
Hi! im asking which Rate is the best to get best result ?
if i use -rate 100 i know that is very slow but do i will have best result then use -rate 10000 ?
Thanks in advance for your response

**Comment by mzpqnxow** [comment]
the best rate is 13,271 ...

There are a lot of factors. Your NIC, the NIC drivers, OS, the circuit, etc, etc. Experiment.

You can close this now

**Comment by H1-N1** [comment]
13 Sep 2018 - 30 Sep 2020 ---> 2year !!
