### ISSUE TITLE
UDP scan and HELLO

### ISSUE THREAD

**Issue by s0i37** [robertdavidgraham/masscan#416]
Hello. I noticed that hello-file/hello-string:
`masscan -pU:1900 1.2.3.4 --hello-file ssdp-query.txt`
don't work:
```
tcpdump -i tap0 -nn host 1.2.3.4
19:57:42.340042 IP 172.123.0.2.45861 > 31.28.102.85.1900: UDP, length 0
```
It sends an empty UDP packet.

**Comment by s0i37** [comment]
ping

**Comment by s0i37** [comment]
masscan -e eth0 -p U:1900 --nmap-payloads ssdp-query.txt 77.77.0.0/16

ssdp-query.txt:
```
	 udp 1900
 	 "M-SEARCH * HTTP/1.1\r\n"
 	 "HOST: 239.255.255.250:1900\r\n"
 	 "MAN: \"ssdp:discover\"\r\n"
 	 "MX: 1\r\n"
 	 "ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\n\r\n"
```

**Comment by mskf3000** [comment]
> masscan -e eth0 -p U:1900 --nmap-payloads ssdp-query.txt 77.77.0.0/16
> 
> ssdp-query.txt:
> 
> ```
> 	 udp 1900
>  	 "M-SEARCH * HTTP/1.1\r\n"
>  	 "HOST: 239.255.255.250:1900\r\n"
>  	 "MAN: \"ssdp:discover\"\r\n"
>  	 "MX: 1\r\n"
>  	 "ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\n\r\n"
> ```

tks
