### ISSUE TITLE
Rework libdl based dynamic lib loading to allow a build-time option for static linking

### ISSUE THREAD

**Issue by mzpqnxow** [robertdavidgraham/masscan#431]
I know these things were done intentionally, but there are currently no build-time dependencies on libpcap, libpfring and liblua with masscan since it was decided to instead  utilize libdl to dynamically load the libraries and find the symbols at runtime. The benefit to this is that the build system does not require these libraries at build time, and I suppose that the shared libraries could be updated without requiring a rebuild of masscan. Am I missing any other benefits?

Anyway, I realize that it would require some annoying `#ifdefs` and changes to the `Makefile` but in my opinion, being able to statically link `masscan` would be convenient in some cases- for example, where your execution environment is more spartan than the build environment, or when your execution environment is just extremely spartan (i.e. an embedded device)

From an ethical perspective, there's obviously the risk of script kiddies spreading/using statially linked builds of `masscan` on compromised/wormed embedded devices, but this can already be done, just with a bunch more work

My use-case is cross-compiling and statically linking `masscan` using musl libc so that I can use it for testing on a router on one of my network edges

Perhaps this is a very rare use case and there is no interest in supporting it. If it is something that would be considered I could submit a PR. As I said I would expect it to be a very small amount of code, mostly cpp directives and some changes to the `Makefile`

Thanks.

**Comment by RoganDawes** [comment]
I'm interested in a masscan build for OpenWRT, which I suspect is what you are talking about. Maybe do a pull request anyway, and those of use who are interested can always apply the patch?

**Comment by ahmedm** [comment]
I'm also interested in an all static MUSL build, It would be great if you could submit a PR and there is no need for Makefile changes just a working define and anyone interested should be able to script the build and override make options

**Comment by Margular** [comment]
I have made a statically linked masscan, you can check it here: https://github.com/Margular/masscan/tree/dev

**Comment by mzpqnxow** [comment]
@Margular, it might be suitable as a PR _if_ you implemented it using cpp conditionals, e.g.

```
#ifdef STATIC
    <static code>
#else
    <original code>
#endif
```

This could then be passed to gcc via a `Makefile` target
