### ISSUE TITLE
pcap_setdirection(IN): Setting direction is not impleme

### ISSUE THREAD

**Issue by blue997** [robertdavidgraham/masscan#454]
Hello, can you tell me how to solve this problem?

**Comment by W1997** [comment]
C:\masscan-1.0.5\masscan-1.0.5\bin
λ masscan.exe -p 80 x.x.24.0/24
pcap_setdirection(IN): Setting direction is not implemented on this platform

Starting masscan 1.0.4 (http://bit.ly/14GZzcT) at 2019-10-10 14:22:43 GMT
 -- forced options: -sS -Pn -n --randomize-hosts -v --send-eth
Initiating SYN Stealth Scan
Scanning 256 hosts [1 port/host]
