### ISSUE TITLE
The scan results of masscan are not reliable

### ISSUE THREAD

**Issue by wangyong-fly** [robertdavidgraham/masscan#463]
I use masscan to scan a nonexistent IP Address ，ports are 0-65535, the shell command is "masscan 132.156.158.6 -p0-65535 --max-rate 1000",   but masscan tells me that all the ports are open. The ip address is not exist, how do it find all the ports are open.  MacBook Pro test result: ` masscan 132.156.158.6 -p0-65535 --max-rate 1000

Starting masscan 1.0.4 (http://bit.ly/14GZzcT) at 2019-11-27 03:17:44 GMT
 -- forced options: -sS -Pn -n --randomize-hosts -v --send-eth
Initiating SYN Stealth Scan
Scanning 1 hosts [65536 ports/host]
Discovered open port 60127/tcp on 132.156.158.6
Discovered open port 23182/tcp on 132.156.158.6
Discovered open port 7365/tcp on 132.156.158.6
Discovered open port 54992/tcp on 132.156.158.6
Discovered open port 60517/tcp on 132.156.158.6
Discovered open port 17799/tcp on 132.156.158.6
Discovered open port 17311/tcp on 132.156.158.6
Discovered open port 63533/tcp on 132.156.158.6
Discovered open port 53833/tcp on 132.156.158.6
Discovered open port 47652/tcp on 132.156.158.6
Discovered open port 35941/tcp on 132.156.158.6
Discovered open port 59262/tcp on 132.156.158.6
Discovered open port 42567/tcp on 132.156.158.6
Discovered open port 48445/tcp on 132.156.158.6
Discovered open port 55306/tcp on 132.156.158.6
Discovered open port 21632/tcp on 132.156.158.6
Discovered open port 2907/tcp on 132.156.158.6
Discovered open port 12063/tcp on 132.156.158.6
Discovered open port 36689/tcp on 132.156.158.6
Discovered open port 20920/tcp on 132.156.158.6
Discovered open port 49555/tcp on 132.156.158.6
Discovered open port 30481/tcp on 132.156.158.6
Discovered open port 42007/tcp on 132.156.158.6
Discovered open port 35899/tcp on 132.156.158.6
Discovered open port 30746/tcp on 132.156.158.6
Discovered open port 328/tcp on 132.156.158.6
Discovered open port 57561/tcp on 132.156.158.6
Discovered open port 47206/tcp on 132.156.158.6
Discovered open port 6337/tcp on 132.156.158.6
Discovered open port 29202/tcp on 132.156.158.6
Discovered open port 54201/tcp on 132.156.158.6
Discovered open port 29148/tcp on 132.156.158.6
Discovered open port 28524/tcp on 132.156.158.6
Discovered open port 12940/tcp on 132.156.158.6
Discovered open port 44169/tcp on 132.156.158.6
Discovered open port 61091/tcp on 132.156.158.6
Discovered open port 46268/tcp on 132.156.158.6
Discovered open port 53873/tcp on 132.156.158.6
Discovered open port 34996/tcp on 132.156.158.6
Discovered open port 25481/tcp on 132.156.158.6
Discovered open port 5650/tcp on 132.156.158.6
Discovered open port 20019/tcp on 132.156.158.6
Discovered open port 26717/tcp on 132.156.158.6
Discovered open port 43186/tcp on 132.156.158.6
Discovered open port 63685/tcp on 132.156.158.6
Discovered open port 43269/tcp on 132.156.158.6
Discovered open port 19703/tcp on 132.156.158.6
Discovered open port 49450/tcp on 132.156.158.6
Discovered open port 59063/tcp on 132.156.158.6
Discovered open port 46101/tcp on 132.156.158.6
Discovered open port 1121/tcp on 132.156.158.6
Discovered open port 31424/tcp on 132.156.158.6
Discovered open port 40482/tcp on 132.156.158.6
Discovered open port 42184/tcp on 132.156.158.6
Discovered open port 10110/tcp on 132.156.158.6
Discovered open port 56256/tcp on 132.156.158.6
Discovered open port 23932/tcp on 132.156.158.6
Discovered open port 43099/tcp on 132.156.158.6
Discovered open port 40381/tcp on 132.156.158.6
Discovered open port 52989/tcp on 132.156.158.6
Discovered open port 32971/tcp on 132.156.158.6
Discovered open port 47290/tcp on 132.156.158.6
Discovered open port 38425/tcp on 132.156.158.6
Discovered open port 39956/tcp on 132.156.158.6
Discovered open port 27966/tcp on 132.156.158.6
Discovered open port 17784/tcp on 132.156.158.6
Discovered open port 48656/tcp on 132.156.158.6
Discovered open port 29176/tcp on 132.156.158.6
Discovered open port 7159/tcp on 132.156.158.6
Discovered open port 22146/tcp on 132.156.158.6
Discovered open port 51425/tcp on 132.156.158.6
Discovered open port 15718/tcp on 132.156.158.6
Discovered open port 32148/tcp on 132.156.158.6
Discovered open port 23157/tcp on 132.156.158.6
Discovered open port 50576/tcp on 132.156.158.6
Discovered open port 49831/tcp on 132.156.158.6
Discovered open port 44623/tcp on 132.156.158.6
Discovered open port 1332/tcp on 132.156.158.6
Discovered open port 50815/tcp on 132.156.158.6
Discovered open port 44054/tcp on 132.156.158.6
Discovered open port 33133/tcp on 132.156.158.6
Discovered open port 3119/tcp on 132.156.158.6
Discovered open port 15554/tcp on 132.156.158.6
Discovered open port 43070/tcp on 132.156.158.6
Discovered open port 21982/tcp on 132.156.158.6
Discovered open port 23134/tcp on 132.156.158.6
Discovered open port 61346/tcp on 132.156.158.6
Discovered open port 29358/tcp on 132.156.158.6
Discovered open port 13955/tcp on 132.156.158.6
Discovered open port 61529/tcp on 132.156.158.6
Discovered open port 58703/tcp on 132.156.158.6
Discovered open port 59829/tcp on 132.156.158.6
Discovered open port 25740/tcp on 132.156.158.6
Discovered open port 57273/tcp on 132.156.158.6
Discovered open port 7373/tcp on 132.156.158.6
Discovered open port 29418/tcp on 132.156.158.6
Discovered open port 14879/tcp on 132.156.158.6
Discovered open port 54791/tcp on 132.156.158.6
Discovered open port 47405/tcp on 132.156.158.6
Discovered open port 50743/tcp on 132.156.158.6
Discovered open port 40663/tcp on 132.156.158.6
Discovered open port 56024/tcp on 132.156.158.6
Discovered open port 43889/tcp on 132.156.158.6
Discovered open port 38306/tcp on 132.156.158.6
Discovered open port 56702/tcp on 132.156.158.6
Discovered open port 52844/tcp on 132.156.158.6`

and in docker test use python-masscan: `': '37', 'endtime': '1574822827', 'services': []}, 23308: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822827', 'services': []}, 62089: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822827', 'services': []}, 10315: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822827', 'services': []}, 8022: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822827', 'services': []}, 46607: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822827', 'services': []}, 45640: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822827', 'services': []}, 30559: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822827', 'services': []}, 32227: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822827', 'services': []}, 61424: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822827', 'services': []}, 44364: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822827', 'services': []}, 37991: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822827', 'services': []}, 3508: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822827', 'services': []}, 54344: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822827', 'services': []}, 36181: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822827', 'services': []}, 48039: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822827', 'services': []}, 52652: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822827', 'services': []}, 47540: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822827', 'services': []}, 22303: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822827', 'services': []}, 13529: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822828', 'services': []}, 5364: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822828', 'services': []}, 28224: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822828', 'services': []}, 5012: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822828', 'services': []}, 14386: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822828', 'services': []}, 37830: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822828', 'services': []}, 26013: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822828', 'services': []}, 9764: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822828', 'services': []}, 64914: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822828', 'services': []}, 57948: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822828', 'services': []}, 45609: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822828', 'services': []}, 16170: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822828', 'services': []}, 56321: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822828', 'services': []}, 62177: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822828', 'services': []}, 21441: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822828', 'services': []}, 19023: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822828', 'services': []}, 15330: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822829', 'services': []}, 19019: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822829', 'services': []}, 49559: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822829', 'services': []}, 12589: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822829', 'services': []}, 32578: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822829', 'services': []}, 60679: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822829', 'services': []}, 7443: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822829', 'services': []}, 43055: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822829', 'services': []}, 40762: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822829', 'services': []}, 63231: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822829', 'services': []}, 12149: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822829', 'services': []}, 44800: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822829', 'services': []}, 57738: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822829', 'services': []}, 1845: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822829', 'services': []}, 50073: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822829', 'services': []}, 61298: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822829', 'services': []}, 27241: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822829', 'services': []}, 34763: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822829', 'services': []}, 61779: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822829', 'services': []}, 40738: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822830', 'services': []}, 3727: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822830', 'services': []}, 15074: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822830', 'services': []}, 5123: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822830', 'services': []}, 44368: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822830', 'services': []}, 11546: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822830', 'services': []}, 5887: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822830', 'services': []}, 32631: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822830', 'services': []}, 54987: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822830', 'services': []}, 26041: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822830', 'services': []}, 7293: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822830', 'services': []}, 34555: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822830', 'services': []}, 38716: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822830', 'services': []}, 60571: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822830', 'services': []}, 24624: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822830', 'services': []}, 32770: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822830', 'services': []}, 7519: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822831', 'services': []}, 10281: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822831', 'services': []}, 531: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822831', 'services': []}, 19654: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822831', 'services': []}, 27379: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822831', 'services': []}, 1003: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822831', 'services': []}, 51417: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822831', 'services': []}, 47365: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822831', 'services': []}, 59716: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822831', 'services': []}, 5399: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822831', 'services': []}, 2036: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822831', 'services': []}, 35139: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822831', 'services': []}, 20149: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822831', 'services': []}, 39112: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822832', 'services': []}, 56244: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822832', 'services': []}, 65172: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822832', 'services': []}, 39921: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822832', 'services': []}, 14948: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822832', 'services': []}, 47823: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822832', 'services': []}, 59424: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822832', 'services': []}, 60730: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822832', 'services': []}, 46166: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822832', 'services': []}, 27859: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822832', 'services': []}, 704: {'state': 'open', 'reason': 'syn-ack', 'reason_ttl': '37', 'endtime': '1574822832', 'services': []}}}}}`

**Comment by mzpqnxow** [comment]
This is not the fault of masscan, it's a behavior of the network
