### ISSUE TITLE
Why the scan rate is so slow?

### ISSUE THREAD

**Issue by yldiscover** [robertdavidgraham/masscan#525]
Hi,
  I have set the rate as 500000,but the masscan's scanning speed is only 300K?
  How to speed up the scan speed?

**Comment by prince911** [comment]
you are so lucky iam 4 kb

**Comment by robertdavidgraham** [comment]
Scan rate is determined by the network drivers of your local computer, including various network hooks that slow down packet transmission. It complicated diagnosing this for each platform.
