### ISSUE TITLE
shards ip  overlap

### ISSUE THREAD

**Issue by Lpker-2006** [robertdavidgraham/masscan#531]
ipfile content:
115.236.1.0-115.236.1.255
115.237.1.0-115.237.1.255

A machine config.ini content:
rate=1000
includefile= ip.txt
output-status = open
ports = 8080
output-filename = result.xml
shards = 2/2

B machine config.ini content:
rate=1000
includefile= ip.txt
output-status = open
ports = 8080
output-filename = result.xml
shards = 1/2

scaned result is overlaping

anybody can tell me why

**Comment by robertdavidgraham** [comment]
You need to also specify the same randomization seed, `--seed 10` for example. I've added a warning message if a shard is specified without a seed.
