### ISSUE TITLE
Non-deterministic FSM?

### ISSUE THREAD

**Issue by Frky** [robertdavidgraham/masscan#534]
It looks to me that there is an issue with the `masscan` implementation of the FSM to parse banners, and that it leads to bugs, for instance, in the parsing of HTTP fields in `proto-http.c`.

In `proto-http.c`, according to my understanding, the following patterns are to be detected by the FSM for HTTP:

```
enum {
    HTTPFIELD_INCOMPLETE,
    HTTPFIELD_SERVER,
    HTTPFIELD_CONTENT_LENGTH,
    HTTPFIELD_CONTENT_TYPE,
    HTTPFIELD_VIA,
    HTTPFIELD_LOCATION,
    HTTPFIELD_UNKNOWN,
    HTTPFIELD_NEWLINE,
};
static struct Patterns http_fields[] = {
    {"Server:",          7, HTTPFIELD_SERVER,           SMACK_ANCHOR_BEGIN},
    //{"Content-Length:", 15, HTTPFIELD_CONTENT_LENGTH,   SMACK_ANCHOR_BEGIN},
    //{"Content-Type:",   13, HTTPFIELD_CONTENT_TYPE,     SMACK_ANCHOR_BEGIN},
    {"Via:",             4, HTTPFIELD_VIA,              SMACK_ANCHOR_BEGIN},
    {"Location:",        9, HTTPFIELD_LOCATION,         SMACK_ANCHOR_BEGIN},
    {":",                1, HTTPFIELD_UNKNOWN, 0},
    {"\n",               1, HTTPFIELD_NEWLINE, 0},
    {0,0,0,0}
};
```

In particular, when the function `smack_search_next` is called on an `HTTP` banner parser as constructed in `proto-http.c#L164`:
* it should be detecting `Server:` in the beginning of the string to parse (because it is anchored) and return `HTTPFIELD_SERVER`;
* it should be detecting `:` anywhere in the string to parse (because it is **not** anchored) and return `HTTPFIELD_UNKNOWN`.

However, I don't understand how the ambiguity of these to cases is handled by the current implementation. 

In other words, when parsing the banner `Server: XXX`, it starts by reading `Server`. At this point, the FSM is in a state (let's call it `SX`) where it expects `:` to complete the pattern `Server:`. However, from *every* state of the FSM, we could also read the character `:` and this would lead to the state where `HTTPFIELD_UNKNOWN` is returned.

**My question is**: *how does the FSM handle the transition when it reads `:` from the state `SX`? How does it handle this ambiguity between the two patterns it tries to detect?*

I gave it a try, and it looks like it doesn't handle it properly: when I try to parse the banner `Server: XXX` with this FSM, I get `HTTPFIELD_UNKNOWN`. To reproduce:

```
$ cd masscan/src
$ cat << EOF > fsm-http-ambiguity.c
#include <string.h>

#include "smack.h"
#include "smackqueue.h"
#include "proto-banner1.h"

/* from proto-http.c */
enum {
    HTTPFIELD_INCOMPLETE,
    HTTPFIELD_SERVER,
    HTTPFIELD_CONTENT_LENGTH,
    HTTPFIELD_CONTENT_TYPE,
    HTTPFIELD_VIA,
    HTTPFIELD_LOCATION,
    HTTPFIELD_UNKNOWN,
    HTTPFIELD_NEWLINE,
};
/* from proto-http.c */
static struct Patterns http_fields[] = {
    {"Server:",          7, HTTPFIELD_SERVER,           SMACK_ANCHOR_BEGIN},
    //{"Content-Length:", 15, HTTPFIELD_CONTENT_LENGTH,   SMACK_ANCHOR_BEGIN},
    //{"Content-Type:",   13, HTTPFIELD_CONTENT_TYPE,     SMACK_ANCHOR_BEGIN},
    {"Via:",             4, HTTPFIELD_VIA,              SMACK_ANCHOR_BEGIN},
    {"Location:",        9, HTTPFIELD_LOCATION,         SMACK_ANCHOR_BEGIN},
    {":",                1, HTTPFIELD_UNKNOWN, 0},
    {"\n",               1, HTTPFIELD_NEWLINE, 0},
    {0,0,0,0}
};

int main(void) {
    size_t i;
    /* create a smack to parse HTTP */
    struct SMACK *smack = smack_create("banner1", SMACK_CASE_INSENSITIVE);
    /* add HTTP fields we want to parse with smack */
    for (i=0; http_fields[i].pattern; i++) {
        smack_add_pattern(
                        smack,
                        http_fields[i].pattern,
                        http_fields[i].pattern_length,
                        http_fields[i].id,
                        http_fields[i].is_anchored);
    }
    smack_compile(smack);
    /* banner to parse */
    char *banner = "Server: void\0";
    printf("Parsing HTTP banner: \"%s\"\n", banner);
    /* starting in initial state, at offset 0 */
    unsigned int state = 0;
    unsigned int offset = 0;
    /* expecting id == HTTPFIELD_SERVER */
    size_t id = smack_search_next(smack, &state, banner, &offset, strlen(banner));
    switch (id) {
        case HTTPFIELD_SERVER:
            printf("[*] TEST OK\n");
            return 0;
        case HTTPFIELD_UNKNOWN:
            printf("[*] TEST KO: expecting HTTPFIELD_SERVER - got HTTPFIELD_UNKNOWN\n");
            return 1;
        default:
            printf("[*] TEST KO: expecting id=%d - got id=%u\n", HTTPFIELD_SERVER, id);
            return 1;
    }
    return 0;
}
EOF
$ gcc -o fsm-http-ambiguity fsm-http-ambiguity.c smack1.c smackqueue.c pixie-timer.c -I.
$ ./fsm-http-ambiguity 
Parsing HTTP banner: "Server: void"
[*] TEST KO: expecting HTTPFIELD_SERVER - got HTTPFIELD_UNKNOWN
```

**Comment by robertdavidgraham** [comment]
Hi. I really need to refactor the HTTP parser as it's gotten pretty ugly and stupid.

I added code to extract the Server: name. Simply add "--banners --capture servername" and it'll capture the HTTP Server: field separately, as in:
  
<img width="1042" alt="Screen Shot 2021-01-13 at 1 39 45 PM" src="https://user-images.githubusercontent.com/3814757/104494736-d5820e80-55a4-11eb-83f8-b0acb11f5463.png">

I think the answer to your question is that once we get a "match", we have to enumerate through several possible matches. In the HTTP parser code, it does it here:
<img width="589" alt="Screen Shot 2021-01-13 at 1 41 28 PM" src="https://user-images.githubusercontent.com/3814757/104494969-285bc600-55a5-11eb-9020-a2de910dd771.png">

**Comment by Frky** [comment]
I didn't see this comment, now it's way clearer.
Thank you for taking time to answer, and for adding the example of the header `Server` in masscan. It was also of great help.
