### ISSUE TITLE
Build failed after last commit

### ISSUE THREAD

**Issue by savushkin-yauheni** [robertdavidgraham/masscan#537]
Hi guys.

after last changes in ` src/main-conf.c`:
 src/main-conf.c:

<img width="871" alt="Screen Shot 2021-01-10 at 11 47 58" src="https://user-images.githubusercontent.com/5173352/104119671-b895d300-5339-11eb-81ea-075531d1e2bb.png">

Could you please check it? 
Thanks.

**Comment by robertdavidgraham** [comment]
Yea, I broke that doing pull requests. I quickly fixed it, though.
