### ISSUE TITLE
Router MAC address ipv6 is not identified correctly

### ISSUE THREAD

**Issue by sc07kvm** [robertdavidgraham/masscan#541]
I wanted to test new IPv6 scanning functionality and launched mass can like this:
`masscan --banners 2600:9000:20fc:a600:3:db06:4200:93a1/128 -p443 -oJ out.json --wait 10 --source-port 61010`
masscan sent a SYN packet, but the server didn’t reply and no errors received. Although it does work with **wget** on the same address:
`wget -6 https://download.docker.com/linux/debian`

The problem is with router MAC address that is set in Ethernet. Masscan takes into account only IPv4, for me it’s different from IPv6 router address:
```
route -6
...
[::]/0                         fe80::225:84ff:fe01:8a40   UGDAe 1024 20     0 enp8s0
...

ip -6 neigh show | grep  fe80::225:84ff:fe01:8a40
fe80::225:84ff:fe01:8a40 dev enp8s0 lladdr _00:25:84:01:8a:40_ router STALE
fe80::225:84ff:fe01:8a40 dev enp9s0 lladdr _00:25:84:01:8a:40_ router STALE
```
```
route -4 -v -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
...
0.0.0.0         213.108.196.1   0.0.0.0         UG    0      0        0 enp8s0
...

arp -n | grep 213.108.196.1
213.108.196.1            ether   _00:1c:73:4e:05:33_   C                     enp8s0
```

Could you fix this IPv6 issue please? Traffic [dumps](https://github.com/robertdavidgraham/masscan/files/5814395/dumps.zip) attached.

**Comment by robertdavidgraham** [comment]
Thanks. I'll work on this.

**Comment by robertdavidgraham** [comment]
I've fixed the issue. It now uses NDP Neighbor Discover Protocol to find the local IPv6 router. You can also configure the MAC address of the IPv6 router manually using either --router-mac <addr> (which also sets the IPv4 router), or --router-mac-ipv6 <addr> to set the MAC address of the IPv6 router separate from the IPv4 router.
