### ISSUE TITLE
error when installing

### ISSUE THREAD

**Issue by evantoday** [robertdavidgraham/masscan#543]
/tmp/masscan# make instal
gcc -g -ggdb    -Wall -O2 -c src/crypto-base64.c -o tmp/crypto-base64.o
gcc -g -ggdb    -Wall -O2 -c src/crypto-blackrock2.c -o tmp/crypto-blackrock2.o
gcc -g -ggdb    -Wall -O2 -c src/event-timeout.c -o tmp/event-timeout.o
gcc -g -ggdb    -Wall -O2 -c src/in-binary.c -o tmp/in-binary.o
gcc -g -ggdb    -Wall -O2 -c src/in-filter.c -o tmp/in-filter.o
gcc -g -ggdb    -Wall -O2 -c src/in-report.c -o tmp/in-report.o
gcc -g -ggdb    -Wall -O2 -c src/logger.c -o tmp/logger.o
src/logger.c: In function ‘vLOGip’:
src/logger.c:55:9: warning: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘char[48]’ [-Wformat=]
         sprintf_s(sz_ip, sizeof(sz_ip), "%s", ipaddress_fmt(ip).string);
         ^
src/logger.c:55:9: warning: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘char[48]’ [-Wformat=]
gcc -g -ggdb    -Wall -O2 -c src/main-conf.c -o tmp/main-conf.o -DGIT=\"1.3.0-35-g4fac37d\"
src/main-conf.c: In function ‘masscan_echo_nic’:
src/main-conf.c:312:17: warning: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘char[48]’ [-Wformat=]
                 ipv4address_fmt(masscan->nic[i].src.ipv4.first).string);
                 ^
src/main-conf.c:336:17: warning: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘char[48]’ [-Wformat=]
                 ipv4address_fmt(masscan->nic[i].src.ipv4.last).string);
                 ^
src/main-conf.c:336:17: warning: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘char[48]’ [-Wformat=]
src/main-conf.c:343:21: warning: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘char[48]’ [-Wformat=]
                     ipv6address_fmt(masscan->nic[i].src.ipv6.last).string);
                     ^
src/main-conf.c:343:21: warning: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘char[48]’ [-Wformat=]
src/main-conf.c:345:13: warning: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘char[48]’ [-Wformat=]
             fprintf(fp, "adapter-ip%s = %s\n", idx_str, ipv6address_fmt(masscan->nic[i].src.ipv6.first).string);
             ^
src/main-conf.c: In function ‘SET_output_format’:
src/main-conf.c:1255:29: warning: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘char[48]’ [-Wformat=]
                             masscan->redis.port);
                             ^
src/main-conf.c: In function ‘masscan_echo’:
src/main-conf.c:2986:9: warning: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘char[48]’ [-Wformat=]
         fprintf(fp, "range = %s", ipv6address_fmt(range.begin).string);
         ^
src/main-conf.c:2993:17: warning: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘char[48]’ [-Wformat=]
                 fprintf(fp, "-%s", ipv6address_fmt(range.end).string);
                 ^
gcc -g -ggdb    -Wall -O2 -c src/main-dedup.c -o tmp/main-dedup.o
src/main-dedup.c: In function ‘dedup_selftest’:
src/main-dedup.c:387:4: warning: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘char[48]’ [-Wformat=]
    port_me);
    ^
src/main-dedup.c:387:4: warning: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘char[48]’ [-Wformat=]
gcc -g -ggdb    -Wall -O2 -c src/main-initadapter.c -o tmp/main-initadapter.o
gcc -g -ggdb    -Wall -O2 -c src/main-listscan.c -o tmp/main-listscan.o
src/main-listscan.c: In function ‘main_listscan’:
src/main-listscan.c:55:13: warning: format ‘%s’ expects argument of type ‘char *’, but argument 2 has type ‘char[48]’ [-Wformat=]
             printf("%s\n", ipaddress_fmt(addr).string);
             ^
src/main-listscan.c:58:17: warning: format ‘%s’ expects argument of type ‘char *’, but argument 2 has type ‘char[48]’ [-Wformat=]
                 printf("[%s]:%u\n", ipaddress_fmt(addr).string, port);
                 ^
src/main-listscan.c:60:17: warning: format ‘%s’ expects argument of type ‘char *’, but argument 2 has type ‘char[48]’ [-Wformat=]
                 printf("%s:%u\n", ipaddress_fmt(addr).string, port);
                 ^
gcc -g -ggdb    -Wall -O2 -c src/main-ptrace.c -o tmp/main-ptrace.o
src/main-ptrace.c: In function ‘packet_trace’:
src/main-ptrace.c:40:15: warning: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘char[48]’ [-Wformat=]
               parsed.port_src);
               ^
src/main-ptrace.c:40:15: warning: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘char[48]’ [-Wformat=]
src/main-ptrace.c:44:15: warning: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘char[48]’ [-Wformat=]
               parsed.port_dst);
               ^
src/main-ptrace.c:44:15: warning: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘char[48]’ [-Wformat=]
gcc -g -ggdb    -Wall -O2 -c src/main-readrange.c -o tmp/main-readrange.o
src/main-readrange.c: In function ‘main_readrange’:
src/main-readrange.c:84:9: warning: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘char[48]’ [-Wformat=]
         fprintf(fp, "%s", ipv6address_fmt(range.begin).string);
         ^
src/main-readrange.c:90:17: warning: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘char[48]’ [-Wformat=]
                 fprintf(fp, "-%s", ipv6address_fmt(range.end).string);
                 ^
gcc -g -ggdb    -Wall -O2 -c src/main-status.c -o tmp/main-status.o
gcc -g -ggdb    -Wall -O2 -c src/main-throttle.c -o tmp/main-throttle.o
gcc -g -ggdb    -Wall -O2 -c src/main.c -o tmp/main.o
gcc -g -ggdb    -Wall -O2 -c src/masscan-app.c -o tmp/masscan-app.o
gcc -g -ggdb    -Wall -O2 -c src/massip-addr.c -o tmp/massip-addr.o
In file included from /usr/include/string.h:635:0,
                 from src/massip-addr.c:2:
src/massip-addr.c: In function ‘ipv6address_selftest’:
src/massip-addr.c:212:9: error: invalid use of non-lvalue array
     if (strcmp(ipaddress_fmt(ip).string, "1.255.0.163") != 0)
         ^
src/massip-addr.c:212:9: error: invalid operands to binary + (have ‘char[48]’ and ‘int’)
     if (strcmp(ipaddress_fmt(ip).string, "1.255.0.163") != 0)
         ^
src/massip-addr.c:212:5: error: cannot convert to a pointer type
     if (strcmp(ipaddress_fmt(ip).string, "1.255.0.163") != 0)
     ^
In file included from /usr/include/string.h:635:0,
                 from src/massip-addr.c:2:
src/massip-addr.c:212:9: error: invalid use of non-lvalue array
     if (strcmp(ipaddress_fmt(ip).string, "1.255.0.163") != 0)
         ^
src/massip-addr.c:212:9: error: invalid operands to binary + (have ‘char[48]’ and ‘int’)
     if (strcmp(ipaddress_fmt(ip).string, "1.255.0.163") != 0)
         ^
src/massip-addr.c:212:5: error: cannot convert to a pointer type
     if (strcmp(ipaddress_fmt(ip).string, "1.255.0.163") != 0)
     ^
In file included from /usr/include/string.h:635:0,
                 from src/massip-addr.c:2:
src/massip-addr.c:212:9: error: invalid use of non-lvalue array
     if (strcmp(ipaddress_fmt(ip).string, "1.255.0.163") != 0)
         ^
src/massip-addr.c:212:9: error: invalid use of non-lvalue array
     if (strcmp(ipaddress_fmt(ip).string, "1.255.0.163") != 0)
         ^
src/massip-addr.c:212:5: error: cannot convert to a pointer type
     if (strcmp(ipaddress_fmt(ip).string, "1.255.0.163") != 0)
     ^
src/massip-addr.c:212:5: error: cannot convert to a pointer type
src/massip-addr.c:212:5: error: cannot convert to a pointer type
src/massip-addr.c:212:5: error: cannot convert to a pointer type
In file included from /usr/include/string.h:635:0,
                 from src/massip-addr.c:2:
src/massip-addr.c:212:9: error: invalid operands to binary + (have ‘char[48]’ and ‘int’)
     if (strcmp(ipaddress_fmt(ip).string, "1.255.0.163") != 0)
         ^
src/massip-addr.c:212:5: error: cannot convert to a pointer type
     if (strcmp(ipaddress_fmt(ip).string, "1.255.0.163") != 0)
     ^
In file included from /usr/include/string.h:635:0,
                 from src/massip-addr.c:2:
src/massip-addr.c:212:9: error: invalid use of non-lvalue array
     if (strcmp(ipaddress_fmt(ip).string, "1.255.0.163") != 0)
         ^
src/massip-addr.c:212:5: error: cannot convert to a pointer type
     if (strcmp(ipaddress_fmt(ip).string, "1.255.0.163") != 0)
     ^
In file included from /usr/include/string.h:635:0,
                 from src/massip-addr.c:2:
src/massip-addr.c:212:9: error: invalid use of non-lvalue array
     if (strcmp(ipaddress_fmt(ip).string, "1.255.0.163") != 0)
         ^
Makefile:104: recipe for target 'tmp/massip-addr.o' failed
make: *** [tmp/massip-addr.o] Error 1

**Comment by robertdavidgraham** [comment]
Can you post your compiler version please (like `gcc --version`)

**Comment by evantoday** [comment]
Fixed sorry for this :+1:

**Comment by shodanalert** [comment]
hello, what is the recommended gcc version to compile masscan ?

I tried to complile on centos7 using gcc version 4.8.5 get this error
`src/massip-addr.c: In function ‘ipv6address_selftest’:
src/massip-addr.c:244:5: error: invalid use of non-lvalue array
`

**Comment by lihaoran93** [comment]
> Fixed sorry for this 👍

How to do fix
