### ISSUE TITLE
Input from file (-iL) ignores line without newline (new in 1.3.0)

### ISSUE THREAD

**Issue by ravenium** [robertdavidgraham/masscan#545]
Hello,

There seems to be a bug that's cropped up as of 1.3.0 where specifying an input file (-iL) without a newline at the end of said file will skip the last item in the file.  

I have a Python script that creates a list of ips, then launches masscan with -iL and the list (sometimes a few hundred ips, sometimes a single CIDR).  When I rebuilt the container recently, I noticed none of my single IP runs were happening.  It looks as though masscan ignores the line if there's no newline (\n) and bails with a message about an empty IP list. If there are multiple lines in the file, it will ignore the very last one.

The temporary workaround is to add a newline at the end of the file before writing.

**Comment by robertdavidgraham** [comment]
This is really annoying. I actually had code there, but after IPv6 changes, forgot to retest it. It should work now.
