### ISSUE TITLE
fast scan get result

### ISSUE THREAD

**Issue by lemorn** [robertdavidgraham/masscan#546]
Hello, I am running masscan on my Amazon server. When I adjust the rate parameter, the scan becomes faster, but the scan results will be less. Is this the reason for bandwidth? If I want to speed up the scan without reducing the number of scans, how should I adjust the server configuration? Under the circumstance that the number of scans remains unchanged, what is the maximum scan rate of masscan?
![image](https://user-images.githubusercontent.com/53805865/105619993-eba88e00-5e32-11eb-9150-9c7a4576fe2b.png)

**Comment by robertdavidgraham** [comment]
I added this to the `doscs/faq` section. It's caused by your infrastructure artificially limiting traffic, so the more you pump out, the more gets dropped.
