### ISSUE TITLE
The IP address field of the masscan scan result in Windows system cannot be displayed normally

### ISSUE THREAD

**Issue by superboy-zjc** [robertdavidgraham/masscan#551]
I have tried both MINGW32 and VS2012 compilation methods, but neither can solve this problem.
![image](https://user-images.githubusercontent.com/60600792/106253612-acbf7180-6252-11eb-8dba-8f16bafae49c.png)

**Comment by superboy-zjc** [comment]
Outputting a file in xml format cannot solve this problem. The IP address field is displayed with abnormal characters.

**Comment by superboy-zjc** [comment]
After testing, this problem only appears in version 1.3.1

**Comment by robertdavidgraham** [comment]
This has been fixed in the latest update.

**Comment by superboy-zjc** [comment]
Thanks!!!Best wishes
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "robertdavidgraham/masscan"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月30日(星期六) 下午3:41
收件人:&nbsp;"robertdavidgraham/masscan"<masscan@noreply.github.com&gt;;
抄送:&nbsp;"钟佳成"<1826599908@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [robertdavidgraham/masscan] The IP address field of the masscan scan result in Windows system cannot be displayed normally (#551)





 
This has been fixed in the latest update.

**Comment by superboy-zjc** [comment]
> This has been fixed in the latest update.

Thanks! Best wishes :)
