### ISSUE TITLE
masscan --top-ports=1000 not working

### ISSUE THREAD

**Issue by nullman0x** [robertdavidgraham/masscan#552]
I tried to run top 1000 ports using masscan

masscan --top-ports=1000 

but not working

masscan --top-ports1000 --rate=1000 --banners -iL ip.txt -oG ip2.txt

**Comment by nullman0x** [comment]
sudo apt install masscan 

installs old version

update that repo

**Comment by robertdavidgraham** [comment]
Seems to be working fine in the latest code. Your example is missing an equals sign:
masscan --top-ports1000 --rate=1000 --banners -iL ip.txt -oG ip2.txt
masscan --top-ports=1000 --rate=1000 --banners -iL ip.txt -oG ip2.txt

I don't know about older versions or whatever may be in a repo.
