### ISSUE TITLE
ERROR: bad packet template

### ISSUE THREAD

**Issue by UberGeekDude** [robertdavidgraham/masscan#554]
Got an update today in Kali Linux (apt update && apt upgrade -y && apt autoremove -y) in a VMware Virtual Machine

# masscan -p22,80 <IP Address range>
ERROR: bad packet template

# masscan --version

Masscan version 1.3.1 ( https://github.com/robertdavidgraham/masscan )
Compiled on: Jan 26 2021 09:40:08
Compiler: gcc 10.2.1 20210110
OS: Linux
CPU: unknown (64 bits)
GIT version: unknown

**Comment by robertdavidgraham** [comment]
I know the bug that's causing this. Kali must've gotten grabbed the version that I checked in before I fixed it a couple hours later.

Do:

sudo apt install gcc gmake
git clone https://github.com/robertdavidgraham/masscan
cd masscan
make -j8
make install


This should get the latest code. There are no real dependencies so this should build easily.

**Comment by UberGeekDude** [comment]
I figured as much.  I already got the update via kali apt-get
Thanks.
