### ISSUE TITLE
masscan user-mode TCP stack

### ISSUE THREAD

**Issue by Zabrane** [robertdavidgraham/masscan#557]
From the [doc](https://github.com/robertdavidgraham/masscan/blob/master/README.md#c10-scalability):
`[..] Masscan has its own built-in TCP stack for grabbing banners from TCP connections. This means it can easily support 10 million concurrent TCP connections, assuming of course that the computer has enough memory.
`

Is it possible to extract the `TCP stack` code and use it as a `standalone lib` to create an HTTP server?

If yes, please advice.

**Comment by robertdavidgraham** [comment]
Hi.
No.

One day I hope to make it so, but right now, it's so optimized for the current task, it's not suited to other tasks.
