### ISSUE TITLE
scan wait   -400-secs, should I explicitly set the wait time

### ISSUE THREAD

**Issue by yangjinhao1234** [robertdavidgraham/masscan#558]
when i use the scanner, it can't stop and wait until -600-secs, 
Should I explicitly set the wait time
![pic](https://user-images.githubusercontent.com/49094575/108813133-5f34eb00-75eb-11eb-9479-23f6e0308906.png)

**Comment by robertdavidgraham** [comment]
There are some issues on some platforms with older versions of _masscan_ where one thread failed to recognize that the other threads had stopped, so would keep waiting forever. You can hit <ctrl-c> <ctrl-c> <ctrl-c> (several times in quick succession) to stop the threads. No data will be lost.

Or, I suggest upgrading to the latest version 1.3.
