### ISSUE TITLE
--resume fails with an unknown config option error

### ISSUE THREAD

**Issue by hatarist** [robertdavidgraham/masscan#559]
Currently I'm able to reproduce it on Linux and OS X with the latest master ([3ad77be62](https://github.com/robertdavidgraham/masscan/commit/3ad77be62180d846e127787d1f7d62174c3a5970)).

1. Start masscan and interrupt it to save the paused.conf:

```
# timeout -s INT 1 masscan -p12345 --rate 1 192.168.1.0/24 --wait 0
...
saving resume file to: paused.conf
```

2. Resume the paused scan:

```
# masscan --resume paused.conf
CONF: unknown config option: nocapture=servername
```

The created `paused.conf` file looks like that:
    
    # resume information
    resume-index = 1
    seed = 5391402425458307641
    rate = 1
    shard = 1/1
    nocapture = servername

I fixed it myself by adding a dummy condition in `src/main-conf.c` ([line ~2371](https://github.com/robertdavidgraham/masscan/blob/master/src/main-conf.c#L2369-L2373)):

    } else if (EQUALS("nocapture", name)) {
        // FIXME: do nothing
    } else {
        fprintf(stderr, "CONF: unknown config option: %s=%s\n", name, value);
        exit(1); 
    }

I spent some time digging into the project with no success, so I finally decided to post here. I don't feel confident about the fix I made, thus I created this issue and not a pull request. Sorry about that!

**Comment by mzpqnxow** [comment]
@hatarist I just put in #559 for this

If you want to test, you can use `git clone https://github.com/mzpqnxow/masscan --branch issue-559` to test

**Comment by mzpqnxow** [comment]
@hatarist you can close this now, the PR was merged
