### ISSUE TITLE
[PR Included] Support (optional) NDJSON output for machine parseable stderr status messages via --json-status

### ISSUE THREAD

**Issue by mzpqnxow** [robertdavidgraham/masscan#562]
By now I know everyone who has needed to has rigged up regular expressions for working with the masscan stderr status updates. I did the same a while ago but eventually created a masscan branch with small modifications that outputs NDJSON instead. When `--json-status` is specified on the command-line or in the configuration file, the line that is printed roughly every second is a valid JSON line. The carriage return was left in deliberately, so it doesn't flood the console vertically.

It would be great if you would take this so I can drop the branch from my fork. Because it's an optional flag and should not impact users unless they explicitly choose to use it, I think there's minimal downside, aside from the format string being very ugly :)

The output should remain identical for current invocations, so it shouldn't break anyone :crossed_fingers: 

The use-case is probably easy to guess- scan "manager" processes that invoke and/or monitor the progress of `masscan` and other tools. This makes it simpler to use `masscan` via a web application or some automated daemon, especially when running in infinite mode, or performing a scan that take a long time to complete

A PR for this will follow

In the interest of keeping the changes minimal, I kept the same variables in the JSON message and added only one additional field- `pps`. There is already a `kpps` value that is a derivative of `pps`, but I prefer to have `pps` exposed directly. Matter of preference, I don't feel too strongly about it though

**Comment by robertdavidgraham** [comment]
Ok, I merged this, but I changed the name to `--ndjson-status` instead of `--json-status`, in case somebody wants an actual JSON instead of NDJSON.
