### ISSUE TITLE
BIG IP meaning

### ISSUE THREAD

**Issue by jaimecoj** [robertdavidgraham/masscan#563]
I see messages like this in console:
Banner on port 15XX/tcp on 142.92.XX.XX: [unknown] BIG-IP: [0x2b3XXXX:148XX] {peer} TCP retransmit timeout
Meaning?

**Comment by jaimecoj** [comment]
I see messages like this in console:

**Comment by robertdavidgraham** [comment]
This is an excellent question. When doing a "--banner" check on a target, `masscan` establishes a TCP connection, and tries to identify the protocol. If it gets something like looks like SSH, then it reports the banner as [SSH]. If it gets something it cannot recognize, it reports the protocol as "[unknown]", and if text, shows the raw text -- whatever it contains. If binary, it'll dump a bunch of hex.

Some firewalls or load balancers produce a text error message on some ports, or in some cases _all_ ports. Thus, if you scan the entire Internet for some random port, you'll get these sorts of messages. BIG-IP is a popular loadbalancer, so everyone who does a wide scale scan will see this message in the results.
