### ISSUE TITLE
Bad version of Masscan installed from APT

### ISSUE THREAD

**Issue by choupit0** [robertdavidgraham/masscan#566]
Hello,

I do not know if I'm wrong but when I try to install Masscan on a fresh Debian version, the version installed is not the same as the apt show package.... Even if I try to install the specific version.

**Debian version**

![Debian_version](https://user-images.githubusercontent.com/47336639/110948502-6b20ec80-830f-11eb-9b88-916c04ad04b4.PNG)

**APT version -> 1.0.5**

![APT_version-1-0-5](https://user-images.githubusercontent.com/47336639/110948545-7c69f900-830f-11eb-8b0f-011fa45d864e.PNG)

**Version installed -> 1.0.4**

![Masscan_version1-0-4](https://user-images.githubusercontent.com/47336639/110948605-8e4b9c00-830f-11eb-9943-e4e8e3f6f82c.PNG)

An idea? Is it a Masscan issue or Debian/APT issue? Or it's me?....

**Comment by mzpqnxow** [comment]
You may want to try `which masscan` to see if you're actually running a locally built version that you installed somewhere (e.g. in /usr/local/bin)

If that's not the issue, you'll have to send this to the maintainer (looks like team+pkg-security@tracker.debian.org)

Either way there's nothing that can be done for you here unfortunately- even if this were an issue with the version string in the masscan source, it will be the package maintainers that need to "fix" it

**Comment by its0x08** [comment]
After locating both versions using `which` command, delete the old one and also check the `$PATH` variable and switch the path of the old one after the path of new one so in future all software being executed with be searched on that path first and then the next one in case in the first dir the bin doesnt exist.
An example..
old path    `PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
new path  `PATH=/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin`

**Comment by choupit0** [comment]
> You may want to try `which masscan` to see if you're actually running a locally built version that you installed somewhere (e.g. in /usr/local/bin)
> 
> If that's not the issue, you'll have to send this to the maintainer (looks like [team+pkg-security@tracker.debian.org](mailto:team+pkg-security@tracker.debian.org))
> 
> Either way there's nothing that can be done for you here unfortunately- even if this were an issue with the version string in the masscan source, it will be the package maintainers that need to "fix" it

**Comment by choupit0** [comment]
> You may want to try `which masscan` to see if you're actually running a locally built version that you installed somewhere (e.g. in /usr/local/bin)
> 
> If that's not the issue, you'll have to send this to the maintainer (looks like [team+pkg-security@tracker.debian.org](mailto:team+pkg-security@tracker.debian.org))
> 
> Either way there's nothing that can be done for you here unfortunately- even if this were an issue with the version string in the masscan source, it will be the package maintainers that need to "fix" it

Unfortunately this is really Masscan 1.0.4 which is running... You are right, I will try to contact the maintainer.

Thank you.

**Comment by mzpqnxow** [comment]
>
> Thank you.
> 

Happy to help, glad you got it sorted

You can close this out now

**Comment by choupit0** [comment]
> You can close this out now (I think it reopened when you commented)

Nope, my bad. I closed it accidentaly.

**Comment by rhertzog** [comment]
Actually, your 1.0.5 tag points to a commit where src/masscan-version.h has 1.0.4:
https://github.com/robertdavidgraham/masscan/releases/tag/1.0.5
https://github.com/robertdavidgraham/masscan/tree/83fbdf6fde8f40573381a546d6b27cc78d77cc85/src
https://github.com/robertdavidgraham/masscan/blob/83fbdf6fde8f40573381a546d6b27cc78d77cc85/src/masscan-version.h

But there's no point in fixing anything here.
