### ISSUE TITLE
top-ports err

### ISSUE THREAD

**Issue by gbiagomba** [robertdavidgraham/masscan#569]
Hello @robertdavidgraham,

When i ran the command `masscan --rate 1000 --banners --open-only --retries 3 ‐‐top-ports 100 -iL targets.list` and i got the below error. 
```
FAIL: unknown command-line parameter "‐‐top-ports"
 [hint] did you want "--‐‐top-ports"?
```

I checked to make sure the version was up to date and reran it but i got the same err. I am running this from `Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64`. Here is the output `masscan -V`
```
Masscan version 1.3.2 ( https://github.com/robertdavidgraham/masscan )
Compiled on: Jan 31 2021 18:23:49
Compiler: gcc Apple LLVM 12.0.0 (clang-1200.0.32.29)
OS: Apple
CPU: x86-Corei7 (64 bits)
GIT version: unknown
```

**Comment by duraki** [comment]
Stop copying and pasting from the Internet, you will never learn.

**Comment by gbiagomba** [comment]
@duraki uh? what are you talking mate?

**Comment by duraki** [comment]
> FAIL: unknown command-line parameter "‐‐top-ports"
> [hint] did you want "--‐‐top-ports"?

`‐‐` is not `--`. Retype the command manually and you'll see it works fine.

**Comment by gbiagomba** [comment]
@duraki i copied the command as typed and pasted what i saw. It appended the extra dash/hyphen...I double and tripple checked the command, even opened a new tab to try it and got the same result.

**Comment by gbiagomba** [comment]
i think i see what you mean the hyphens in the top port were shorter. I will try fixing that and seeing what changes
