### ISSUE TITLE
fix

### ISSUE THREAD

**Issue by Cooper66** [robertdavidgraham/masscan#576]
When can I wait for this error to be fixed:
the **--resume paused.conf** option does not work
**CONF: unknown config option: nocapture=servername** 

Version 1.3.2
Build vs10

**Comment by robertdavidgraham** [comment]
Fixed in latest code.

**Comment by device-asdf** [comment]
I'm on version 2:1.3.2+ds1-1 and i'm also getting this error when resuming the scan.

**Comment by duraki** [comment]
@device-asdf

Not sure what you are talking about. You are probably looking at older `masscan` verison (check your `$PATH`!!!)

Anyway, compiling from master does indeed fix the bug. Release soon? Brew still installs the old one.

```
$ masscan -V

Masscan version 1.3.2 ( https://github.com/robertdavidgraham/masscan )
Compiled on: Apr 18 2021 08:57:23
Compiler: gcc Apple LLVM 12.0.0 (clang-1200.0.32.2)
OS: Apple
CPU: unknown (64 bits)
GIT version: 1.3.2-23-g2895fa0

$ masscan --resume paused.conf
Starting masscan 1.3.2 (.....) at 2021-04-18 06:58:55 GMT
Initiating SYN Stealth Scan
Scanning 766976 hosts [1000 ports/host]
rate: 98.62-kpps, 56.62% done,   0:55:02 remaining, found=x
```
