### ISSUE TITLE
Add file scanning with ip list (not about ip range) available

### ISSUE THREAD

**Issue by Multiple-Personality** [robertdavidgraham/masscan#578]
For example
I scanned the entire ip with port 22 saved the file 22.txt
Next time I don't want to do a full scan I just want to scan the 22.txt file to see which ip still works
I hope you can add your own software

**Comment by robertdavidgraham** [comment]
You can read in a file containing IP addresses with `-iL <filename>` or `--include-file <filename>`. You can use many command-line tools (like `cut`) to pull the IP addresses from a prior output.
