### ISSUE TITLE
I asked it to scan an internal /16 network where I know there are about 200 hosts with port 21, and yet it showed only 2

### ISSUE THREAD

**Issue by StewAlexander-com** [robertdavidgraham/masscan#582]
Hi

I ran the same scan with masscan that I did with nmap for devices in a /16 network, and nmap found roughly 200, and although masscan was considerably faster I got only 2 hosts in the same subnet

I downloaded masscan using apt, and I am running Ubuntu 20 as a virtualbox vm

Thanks...

**Comment by xiaoqi7654321** [comment]
Have you solved the problem ?

**Comment by StewAlexander-com** [comment]
No, but I just use nmap

If anyone wants to work on this, please let me know, thanks

**Comment by StewAlexander-com** [comment]
I see, well thanks @mzpqnxow 

Basically useless under my current configuration, might come back to this if I have a device dedicated to scanning
