### ISSUE TITLE
Cross-compiling under MinGW failed due to the lack of the inet_ntop function

### ISSUE THREAD

**Issue by drygdryg** [robertdavidgraham/masscan#584]
I tried to cross-compile masscan on Arch Linux for Windows, and faced the error:
```
/usr/lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld: tmp/rawsock-getip6.o: in function `rawsock_get_adapter_ipv6':
/home/victor/git/masscan/src/rawsock-getip6.c:161: undefined reference to `inet_ntop'
collect2: error: ld returned 1 exit status
make: *** [Makefile:112: bin/masscan] Error 1
```
I was able to fix this by defining the `inet_ntop` function manually. It helped me: https://sourceforge.net/p/mingw/mailman/message/26849634/

Other than that, I ran into a lot of issues, but was able to fix them, here's the patch: https://gist.github.com/drygdryg/06c94e1d6262103dddb0472bc326799a

**Comment by asheroto** [comment]
Thanks for this. How do you apply the patch? Can't seem to find any documentation.

**Comment by drygdryg** [comment]
> Thanks for this. How do you apply the patch? Can't seem to find any documentation.

Place the `mingw.patch` file in the masscan root folder, and then apply it:
```
git apply mingw.patch
```

**Comment by asheroto** [comment]
Thanks for that. For some reason I'm not having any luck.  Cloned repo, put mingw.patch inside masscan folder, applied patch, then make. Using MinGW.

![image](https://user-images.githubusercontent.com/49938263/119277380-e7279280-bbe4-11eb-9d73-5bb17077a7c4.png)

**Comment by drygdryg** [comment]
> Thanks for that. For some reason I'm not having any luck. Cloned repo, put mingw.patch inside masscan folder, applied patch, then make. Using MinGW.

I tried compiling this on Windows, but realized it was quite difficult, so I successfully cross-compiled this on Arch Linux

**Comment by robertdavidgraham** [comment]
I removed the `inet_ntop` function. It wasn't really necessary anyway.

**Comment by asheroto** [comment]
![image](https://user-images.githubusercontent.com/49938263/119436502-e4f72e00-bce1-11eb-949d-8b55e967e627.png)
