### ISSUE TITLE
can't make

### ISSUE THREAD

**Issue by mathoyus** [robertdavidgraham/masscan#589]
root@ubuntu:~/masscan# make
gcc -g -ggdb    -Wall -O2 -c src/crypto-base64.c -o tmp/crypto-base64.o
gcc -g -ggdb    -Wall -O2 -c src/crypto-blackrock2.c -o tmp/crypto-blackrock2.o
gcc -g -ggdb    -Wall -O2 -c src/event-timeout.c -o tmp/event-timeout.o
gcc -g -ggdb    -Wall -O2 -c src/in-binary.c -o tmp/in-binary.o
gcc -g -ggdb    -Wall -O2 -c src/in-filter.c -o tmp/in-filter.o
gcc -g -ggdb    -Wall -O2 -c src/in-report.c -o tmp/in-report.o
gcc -g -ggdb    -Wall -O2 -c src/logger.c -o tmp/logger.o
gcc -g -ggdb    -Wall -O2 -c src/main-conf.c -o tmp/main-conf.o -DGIT=\"1.3.2-23-g2895fa0\"
src/main-conf.c: In function ‘masscan_read_config_file’:
src/main-conf.c:3117:15: warning: ignoring return value of ‘getcwd’, declared with attribute warn_unused_result [-Wunused-result]
         getcwd(dir, sizeof(dir));
               ^
gcc -g -ggdb    -Wall -O2 -c src/main-dedup.c -o tmp/main-dedup.o
gcc -g -ggdb    -Wall -O2 -c src/main-initadapter.c -o tmp/main-initadapter.o
gcc -g -ggdb    -Wall -O2 -c src/main-listscan.c -o tmp/main-listscan.o
gcc -g -ggdb    -Wall -O2 -c src/main-ptrace.c -o tmp/main-ptrace.o
gcc -g -ggdb    -Wall -O2 -c src/main-readrange.c -o tmp/main-readrange.o
gcc -g -ggdb    -Wall -O2 -c src/main-status.c -o tmp/main-status.o
gcc -g -ggdb    -Wall -O2 -c src/main-throttle.c -o tmp/main-throttle.o
gcc -g -ggdb    -Wall -O2 -c src/main.c -o tmp/main.o
gcc -g -ggdb    -Wall -O2 -c src/masscan-app.c -o tmp/masscan-app.o
gcc -g -ggdb    -Wall -O2 -c src/massip-addr.c -o tmp/massip-addr.o
src/massip-addr.c: In function ‘ipv6address_selftest’:
src/massip-addr.c:244:5: error: invalid use of non-lvalue array
     if (strcmp(ipaddress_fmt(ip).string, "1.255.0.163") != 0)
     ^
In file included from /usr/include/string.h:635:0,
                 from src/massip-addr.c:2:
src/massip-addr.c:244:9: error: invalid operands to binary + (have ‘char[48]’ and ‘int’)
     if (strcmp(ipaddress_fmt(ip).string, "1.255.0.163") != 0)
         ^
src/massip-addr.c:244:5: error: cannot convert to a pointer type
     if (strcmp(ipaddress_fmt(ip).string, "1.255.0.163") != 0)
     ^
src/massip-addr.c:244:5: error: invalid use of non-lvalue array
In file included from /usr/include/string.h:635:0,
                 from src/massip-addr.c:2:
src/massip-addr.c:244:9: error: invalid operands to binary + (have ‘char[48]’ and ‘int’)
     if (strcmp(ipaddress_fmt(ip).string, "1.255.0.163") != 0)
         ^
src/massip-addr.c:244:5: error: cannot convert to a pointer type
     if (strcmp(ipaddress_fmt(ip).string, "1.255.0.163") != 0)
     ^
src/massip-addr.c:244:5: error: invalid use of non-lvalue array
src/massip-addr.c:244:5: error: invalid use of non-lvalue array
src/massip-addr.c:244:5: error: cannot convert to a pointer type
src/massip-addr.c:244:5: error: cannot convert to a pointer type
src/massip-addr.c:244:5: error: cannot convert to a pointer type
src/massip-addr.c:244:5: error: cannot convert to a pointer type
In file included from /usr/include/string.h:635:0,
                 from src/massip-addr.c:2:
src/massip-addr.c:244:9: error: invalid operands to binary + (have ‘char[48]’ and ‘int’)
     if (strcmp(ipaddress_fmt(ip).string, "1.255.0.163") != 0)
         ^
src/massip-addr.c:244:5: error: cannot convert to a pointer type
     if (strcmp(ipaddress_fmt(ip).string, "1.255.0.163") != 0)
     ^
src/massip-addr.c:244:5: error: invalid use of non-lvalue array
src/massip-addr.c:244:5: error: cannot convert to a pointer type
src/massip-addr.c:244:5: error: invalid use of non-lvalue array
make: *** [tmp/massip-addr.o] Error 1

**Comment by robertdavidgraham** [comment]
Thanks, this should be fixed now.
