### ISSUE TITLE
IPs

### ISSUE THREAD

**Issue by Walkerip** [robertdavidgraham/masscan#597]
Pls can you help me with how to generate IPS for my masscan ?

**Comment by robertdavidgraham** [comment]
I don't understand the question.

**Comment by Walkerip** [comment]
How can i get Internet Protocol (IPs) for my smtp scanner pls?
[sample.txt](https://github.com/robertdavidgraham/masscan/files/6779996/sample.txt)

**Comment by Walkerip** [comment]
using python
