### ISSUE TITLE
It is suspected that there is a vulnerability in masscan. Scanning customized services will be subject to reverse attack

### ISSUE THREAD

**Issue by hktalent** [robertdavidgraham/masscan#650]
When I scan the whole network of some countries, I find that the response packets returned by the other party will always cause me to crash and restart the system

My system is MacOS 12.2.1 (21d62)

masscan -V

Masscan version 1.3.2 ( https://github.com/robertdavidgraham/masscan )
Compiled on: Jan 31 2021 18:24:32
Compiler: gcc Apple LLVM 12.0.0 (clang-1200.0.32.29)
OS: Apple
CPU: x86-Corei7 (64 bits)
GIT version: unknown

**Comment by scriptzteam** [comment]
weak network?
we scanned (still scanning) 750million of ips, no single crash

**Comment by hktalent** [comment]
@ scriptzteam Maybe I have encountered a scan reversal. Maybe there is a bug in the MacOS version, or it is a bug in the MacOS itself
