### ISSUE TITLE
Masscan Freezes on my 8g raspi

### ISSUE THREAD

**Issue by outercloudstudio** [robertdavidgraham/masscan#696]
I was running masscan on my raspi for the port 25565 but when I woke up the progress was stuck at 0.3% and would not continue any further. The actual command had not quit yet so I hit Ctrl + c to cancel it. I have a seeking suspicion that my raspi went to sleep or something but I thought I disabled screen blanking in the settings. If you need me to post the command I can.

**Comment by outercloudstudio** [comment]
After further testing I have discovered that the program is actually running fine, however the std output fails.

**Comment by outercloudstudio** [comment]
Issues I revise my statement, the std output and packet sending both become paused.

**Comment by robertdavidgraham** [comment]
I tried multiple ways to replicate this but I can't get it to freeze, so I'm closing the ticket.
![image](https://github.com/robertdavidgraham/masscan/assets/3814757/012e8357-a876-45a8-8a70-1d3df59bbedb)
