### ISSUE TITLE
masscan scans all ports, regardless of what -p is set to

### ISSUE THREAD

**Issue by ghost** [robertdavidgraham/masscan#709]
![image](https://user-images.githubusercontent.com/77245194/221275975-83d2f03b-04b9-4349-bf70-6c619303db32.png)

tested on 1.3.2 *and* github master

**Comment by BasToTheMax** [comment]
Use `-p 80` (with a space between the p and the 80)

**Comment by robertdavidgraham** [comment]
Both `-p80` and `-p 80` should work just fine.
I'm at a loss here. I suspect there's a setting in `/etc/masscan/masscan.conf` that somebody added for all ports. If you remove the `-p80` completely, it should tell you that no ports were configured and refuse to run. This would confirm a setting in the conf file. Or you could look in /etc/masscan and see if it's there.
