### ISSUE TITLE
Homepage Link (I assume) is a 404

### ISSUE THREAD

**Issue by TurtleWilly** [robertdavidgraham/masscan#710]
```
Starting masscan 1.3.2 (http://bit.ly/14GZzcT) at 2023-03-18 03:39:01 GMT
```

->

"**Something's wrong here.**

This is a 404 error, which means you've clicked on a bad link or entered an invalid URL. Maybe what you are looking for can be found at Bitly.com. P.S. Bitly links are case sensitive."

**Comment by robertdavidgraham** [comment]
I've tested this out and it appears to be working fine. Maybe a temporary error?

**Comment by TurtleWilly** [comment]
Looks, like it is working now, indeed. I still would prefer, if it simply would display the real URL (it's not that long: "https://github.com/robertdavidgraham/masscan") rather than redirecting the user over another service. It also would be more transparent. Any shortened URLs usually give me the creeps at least (as you never know where you'll end up).
