### ISSUE TITLE
What is this tool and is it malicious?

### ISSUE THREAD

**Issue by BreadTeleporter** [robertdavidgraham/masscan#721]
My website was visited by your tool, leaving 3 requests logged in my nginx logs file, all on the same day.
`IP-ADDRESS - - [07/Jun/2023:12:10:27 +0100] "GET / HTTP/1.0" 200 5076 "-" "masscan/1.3 (https://github.com/robertdavidgraham/masscan)"`

Came here from the useragent string and was just wondering if I should be concerned about these requests.

**Comment by AdmiralNoisyBottom** [comment]
I've seen the same thing in my logs. While there is nothing wrong with port scanning, it is what is done with found ports that trouble me. I think they are just looking for open ports, and therefore services they can look at more closely.
