### ISSUE TITLE
exclude.conf contains an email with confidentiality notice

### ISSUE THREAD

**Issue by OrbiterToad** [robertdavidgraham/masscan#722]
`exclude.conf` contains an email with following confidentiality notice that

_... is intended only for use by the addressee(s) named herein ..._

_... distribution or copying of this email, and any attachments thereto, is strictly prohibited ..._

_... If you receive this in error ... permanently delete the original copy and any copy of any e-mail, and any printout ..._

https://github.com/robertdavidgraham/masscan/blob/9065684c52682d3e12a35559ef72cd0f07838bff/data/exclude.conf#L266

**Comment by robertdavidgraham** [comment]
Yes, it does. I don't honor them. It's basic journalistic ethics -- you can ask for confidentiality before sending something, but demanding confidentiality as you send something is rude.
