### ISSUE TITLE
very slow scan after switching internet

### ISSUE THREAD

**Issue by dw1ghtschrute** [robertdavidgraham/masscan#731]
Hello, I recently changed my internet connection and I am no longer able to use the program. Before the change, it worked perfectly, but now, every time I try to scan, it starts with a fast speed and when it gets close to 150 it becomes extremely slow. I believe it's a block from my internet provider, is there any way to bypass this? With my old internet, I got 100k results, now at the end of the scan I only get 3k. The problem happens with the use of VPN and without. 

![masscanissue](https://github.com/robertdavidgraham/masscan/assets/143866238/4a8cf4da-84d1-47ae-b859-df9bcfe7bbf9)

**Comment by Logan147** [comment]
有人知道怎么绕过吗
