### ISSUE TITLE
Windows 10 - built on mingw64 - "could not determine default interface"

### ISSUE THREAD

**Issue by bill-e-ghote** [robertdavidgraham/masscan#734]
![image](https://github.com/robertdavidgraham/masscan/assets/2491041/f1f526e1-db4f-45ed-97b8-0365784017f1)

I have Npcap installed. I am running as a regular user without local administrator privileges.

**Comment by bill-e-ghote** [comment]
![image](https://github.com/robertdavidgraham/masscan/assets/2491041/94bd7d99-bbca-4762-b0e7-2b203c9175b2)

**Comment by bill-e-ghote** [comment]
![image](https://github.com/robertdavidgraham/masscan/assets/2491041/2e0bef0f-fd9e-4778-b03d-5d81804b2a7d)

**Comment by robertdavidgraham** [comment]
I've cleaned `mingw` things up a bunch working with multiple different types in  32-bit and 64-bit mode. I think I might've fixed it. If not, could you please tell me which type of `mingw` you have installed? There are so many.
![image](https://github.com/robertdavidgraham/masscan/assets/3814757/10127ac9-921d-42f0-a68a-6560eff89333)

**Comment by robertdavidgraham** [comment]
I'm going to close this issue because I think I *might've* fixed it. please re-open if I haven't.

**Comment by bill-e-ghote** [comment]
Hi Rob,

Apologies for my long-delayed response. I just cloned the repo into a clean folder. I'm going to guess that masscan requires one to have Admin or SYSTEM privileges in order to access the network devices other than NPF_Loopback? I do not have Admin privs on this work computer.

$ uname -a
MSYS_NT-10.0-19045 ETG-HP840-30X0T 3.4.10.x86_64 2023-12-22 10:06 UTC x86_64 Msys

Msys2 is installed from here and provides multiple shell environments.
https://www.msys2.org/

Compilation fails in the MSYS2 MSYS shell but succeeds in an MSYS2 MINGW64 shell, albeit with one warning:

![image](https://github.com/robertdavidgraham/masscan/assets/2491041/610d3887-6f74-4270-8534-dcaf7a4a53c3)

![image](https://github.com/robertdavidgraham/masscan/assets/2491041/241d19d6-4a39-45df-a323-e80323af7154)

**Comment by bill-e-ghote** [comment]
This is Wireshark installed using pacman from within Msys2. The messaging reinforces the need to start service 'npf' as Admin in order to be able to utilize packet capture methods. We may as well keep this one closed as the root problem is my not having "root".

![image](https://github.com/robertdavidgraham/masscan/assets/2491041/60547041-f8dd-499e-8008-b01c315ddc28)
