### ISSUE TITLE
--readscan produces "unknown file format (expeced "masscan/1.1")"

### ISSUE THREAD

**Issue by mikedesu** [robertdavidgraham/masscan#752]
```
masscan --version
Masscan version 1.3.2 ( https://github.com/robertdavidgraham/masscan )
Compiled on: Mar  2 2023 21:21:59
Compiler: gcc 11.3.0
OS: Linux
CPU: unknown (64 bits)
GIT version: 1.3.2-54-g144c527
```

Command ran originally before running into unknown file format:

```
masscan `cat ips-1 | tr '\n' ','` -p- -oG masscan-2.bin --rate 20
```

**Comment by mzpqnxow** [comment]
> ```
> 
> masscan --version
> 
> Masscan version 1.3.2 ( https://github.com/robertdavidgraham/masscan )
> 
> Compiled on: Mar  2 2023 21:21:59
> 
> Compiler: gcc 11.3.0
> 
> OS: Linux
> 
> CPU: unknown (64 bits)
> 
> GIT version: 1.3.2-54-g144c527
> 
> ```
> 
> 
> 
> Command ran originally before running into unknown file format:
> 
> 
> 
> ```
> 
> masscan `cat ips-1 | tr '\n' ','` -p- -oG masscan-2.bin --rate 20
> 
> ```
> 
> 

--readscan is only for reading files produced by -oB. You can't --readscan on the greppable (or any other) output formats
