### ISSUE TITLE
please add featrue  which suport SOCKS5  proxy scan 

### ISSUE THREAD

**Issue by peiqiF4ck** [robertdavidgraham/masscan#760]
please add featrue  which suport SOCKS5  proxy scan  thank you

**Comment by mzpqnxow** [comment]
> please add featrue  which suport SOCKS5  proxy scan  thank you 

This is not technically possible, SOCKS is designed to facilitate full connections. It  doesn't work at the layer required to accommodate masscan

**Comment by peiqiF4ck** [comment]
> > please add featrue  which suport SOCKS5  proxy scan  thank you
> 
> This is not technically possible, SOCKS is designed to facilitate full connections. It doesn't work at the layer required to accommodate masscan

ok i see such as ping arp 。thk bro
