### ISSUE TITLE
masscan cannot be stopped in the docekr environment

### ISSUE THREAD

**Issue by muddlelife** [robertdavidgraham/masscan#788]
I found that masscan did not stop in docker environment, version 1.3.2, and no matter whether it was debian, ubuntu or alpine,When I set "wait" to 10, it turned out to be a negative number of seconds

<img width="774" alt="image" src="https://github.com/user-attachments/assets/16d125c1-72cd-4afe-aadd-f844ae45ecd7">

**Comment by mzpqnxow** [comment]
Did you try building from git or is that from the OS package manager?

**Comment by muddlelife** [comment]
I tried both ways, I installed with apt and compiled with source code, but it didn't work

**Comment by mzpqnxow** [comment]
You can add -vvv and see what might be going on, but it seems the exit of the tx thread was missed

If you use a lower rate (e.g. 1000) do you still see that behavior?

Also, to be clear, does this only happen when using --wait or did you add that as an attempted workaround?

**Comment by muddlelife** [comment]
masscan 82.222.44.13 -p 1-65535 --rate 10000 --wait 10 -oJ - -vvv
<img width="961" alt="image" src="https://github.com/user-attachments/assets/ccd2b85e-1d56-482e-a57f-b3f5f558b3ae">
masscan 82.222.44.13 -p 1-65535 --rate 1000 --wait 10 -oJ - -vvv
<img width="1410" alt="image" src="https://github.com/user-attachments/assets/46bb7b60-b97e-44dc-bc59-8744e888195e">
masscan 82.222.44.13 -p 1-65535 --rate 1000 
<img width="783" alt="image" src="https://github.com/user-attachments/assets/f4027430-9535-4af4-a820-25832573588c">

I think this is a general problem, as long as you execute masscan in docker, no matter what parameters you carry, the waiting time will be negative, and it will never stop

**Comment by borisgurzhovski-itgma** [comment]
I have the same issue. Anything new on this?

**Comment by berishaerblin** [comment]
I have the same issue

**Comment by mlec1** [comment]
We had the issue with **bullseye** and **bookworm** images with the official last version `1.3.2`, but building from source from the latest git commit on master everything works on bullseye and bookworm images

**Comment by muddlelife** [comment]
As an update, I tried masscan scanning in docker environment again, using git to get the master branch, and found that there was no problem after compiling by myself, as shown in the figure below
![图片](https://github.com/user-attachments/assets/29ba9ac6-5647-460d-bfab-f1d8823cb1dc)
I think it's a version problem, I'm using version 1.3.9 now, it's normal, it's perfect

**Comment by mzpqnxow** [comment]
> As an update, I tried masscan scanning in docker environment again, using git to get the master branch, and found that there was no problem after compiling by myself, as shown in the figure below
> 
> ![图片](https://github.com/user-attachments/assets/005f1693-da89-48c0-bb01-ae37e71a6033)
> 
> I think it's a version problem, I'm using version 1.3.9 now, it's normal, it's perfect

And this is exactly why my first question was "are using a package or did you build from master" ... 

😀 

I think you can close the issue

**Comment by muddlelife** [comment]
Yes, thank you very much
