### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by pedropnaves** [robertdavidgraham/masscan#92]
Hi,

When i do make i got the following error:

make
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/crypto-base64.c -o tmp/crypto-base64.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/crypto-blackrock2.c -o tmp/crypto-blackrock2.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/event-timeout.c -o tmp/event-timeout.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/in-binary.c -o tmp/in-binary.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/logger.c -o tmp/logger.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/main.c -o tmp/main.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/main-conf.c -o tmp/main-conf.o -DGIT=\"1.0.3-15-ga7bc4ae\"
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/main-dedup.c -o tmp/main-dedup.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/main-initadapter.c -o tmp/main-initadapter.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/main-listscan.c -o tmp/main-listscan.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/main-ptrace.c -o tmp/main-ptrace.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/main-readrange.c -o tmp/main-readrange.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/main-src.c -o tmp/main-src.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/main-status.c -o tmp/main-status.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/main-throttle.c -o tmp/main-throttle.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/masscan-app.c -o tmp/masscan-app.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/out-binary.c -o tmp/out-binary.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/out-grepable.c -o tmp/out-grepable.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/out-null.c -o tmp/out-null.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/output.c -o tmp/output.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/out-redis.c -o tmp/out-redis.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/out-text.c -o tmp/out-text.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/out-xml.c -o tmp/out-xml.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/pixie-backtrace.c -o tmp/pixie-backtrace.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/pixie-file.c -o tmp/pixie-file.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/pixie-threads.c -o tmp/pixie-threads.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/pixie-timer.c -o tmp/pixie-timer.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/proto-arp.c -o tmp/proto-arp.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/proto-banner1.c -o tmp/proto-banner1.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/proto-banout.c -o tmp/proto-banout.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/proto-dns.c -o tmp/proto-dns.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/proto-http.c -o tmp/proto-http.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/proto-icmp.c -o tmp/proto-icmp.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/proto-netbios.c -o tmp/proto-netbios.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/proto-ntp.c -o tmp/proto-ntp.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/proto-preprocess.c -o tmp/proto-preprocess.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/proto-sctp.c -o tmp/proto-sctp.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/proto-snmp.c -o tmp/proto-snmp.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/proto-ssh.c -o tmp/proto-ssh.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/proto-ssl.c -o tmp/proto-ssl.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/proto-ssl-test.c -o tmp/proto-ssl-test.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/proto-tcp.c -o tmp/proto-tcp.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/proto-tcp-telnet.c -o tmp/proto-tcp-telnet.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/proto-udp.c -o tmp/proto-udp.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/proto-x509.c -o tmp/proto-x509.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/proto-zeroaccess.c -o tmp/proto-zeroaccess.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/rand-blackrock.c -o tmp/rand-blackrock.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/rand-lcg.c -o tmp/rand-lcg.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/rand-primegen.c -o tmp/rand-primegen.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/ranges.c -o tmp/ranges.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/rawsock-arp.c -o tmp/rawsock-arp.o
gcc -g -ggdb -rdynamic -pg   -Wall -O3 -c src/rawsock.c -o tmp/rawsock.o
src/rawsock.c:16:18: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
                  ^
compilation terminated.
make: *\* [tmp/rawsock.o] Erro 1

Ubuntu 13.10
How should I proceed? thx

**Comment by sanampuri** [comment]
i am also Facing the same Issue i tried the above Command, But the Issue is Not resolved.
i am Getting error ""Unable to locate package libpcap-dev"
